## test.yml

name: Main workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build with GitHub Pages
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs
        destination: ./docs/_site
        future: false
        token: ${{ github.token }}
